### ISSUE TITLE
A `LICENSE` File is needed for your project

### ISSUE THREAD

**Issue by tcoyvwac** [grassking100/messenger#2]
Hi @grassking100, you have a cool project! :smile_cat: 
I would like to make a Pull Request to your code, but you need a `LICENSE` file for your project.
May I suggest adding the `Apache License 2.0` to your project? The `MIT `license is also ok as a 2nd place choice.

If you need help with this, would you like me to make a GitHub PR to add the `LICENSE` file to your project?

**Comment by grassking100** [comment]
Hello @tcoyvwac, thank you for your appreciation. :smile:
Currently, I decide to put the repository under the license shown in [here](https://github.com/grassking100/messenger/blob/master/LICENSE.md).
 :star2: The pull requests are always welcome!  :star2:

**Comment by tcoyvwac** [comment]
Thanks for adding the `LICENSE` file @grassking100. It's great that you accept PRs and would like to share your project with others around the world! :smile_cat: 
I see that currently, the `LICENSE` for the project is `Creative Commons CC-BY-NC`. Sadly @grassking100, this licence is strongly not recommended for software-based projects.

From the official [Creative Commons FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software):
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses listed as free by the Free Software Foundation and listed as “open source” by the Open Source Initiative.

> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. 

@grassking100 I see that you would like to use `CC-BY-NC`, so may I recommend `GPLv3` to you as a good license for your project? This means that any changes to your project continue to be open to users any time your project is shared to others. 
By the way, I recommend `MPL2.0` (2nd Choice) and `LGPLv3` (3rd Choice) if you are actively making a commercial version of your project.

**Comment by grassking100** [comment]
Hello @tcoyvwac:
I have studied the licenses for a couple of days. so I decide to use the project under the Apache License.
